# Objetivo

O objetivo deste notebook é de calcular e demonstrar o grafico de histograma com valores pré-definidos

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [24]:
def histogram(D, x):
    """
    This function calculate a histogram function
    D: Data array
    X: Length of box
    """
    aux = np.zeros(len(D), dtype = int)
    for i in range(len(D)):
        aux[i] = int((D[i] - min(D))/x)
        
        print(aux)
    saida = np.zeros(1)
    for i in range(len(aux)):
        
    #print(saida)

In [38]:
def hist_aula(data, numbins):
    binsize = (max(data) - min(data))/numbins
    hist = np.zeros(numbins, dtype = int)
    min_value = min(data)
    
    for value in data:
        bin_index = int((value - min_value)/binsize)
        if bin_index >= len(hist):
            bin_index -= 1
        hist[bin_index] += 1
    return hist
        

In [39]:
print(hist_aula([2, 4, 5, 1, 3, 7, 10, 1, 4, 2], 3))

[5 3 2]


In [25]:
histogram([1,2,3,4,5,6], 2)

[0 0 0 0 0 0]
[0 0 0 0 0 0]
[0 0 1 0 0 0]
[0 0 1 1 0 0]
[0 0 1 1 2 0]
[0 0 1 1 2 2]
